# Generated by Django 3.0.4 on 2020-07-05 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_auto_20200705_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Profession',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='name_a',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='name_b',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='media_file/avatar/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
