# Generated by Django 3.0.4 on 2020-07-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20200705_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='author',
            new_name='user',
        ),
    ]
